<a href="https://colab.research.google.com/github/LeeSuBin-khu/tensorflow/blob/master/NLP_deepLearning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
pip install numpy

In [4]:
pip install tensorflow

In [5]:
pip install keras

In [6]:
import numpy as np

In [7]:
import tensorflow as tf

In [8]:
from tensorflow.keras.layers import SimpleRNN

In [9]:
SimpleRNN(units, return_sequences=False, return_state=False)

NameError: ignored

In [11]:
#임의의 입력 데이터를 (1, 4, 5)크기로 생성 
train_X = [[[0.1, 4.2, 1.5, 1.1, 2.8], [1.0, 3.1, 2.5, 0.7, 1.1], [0.3, 2.1, 1.5, 2.1, 0.1], [2.2, 1.4, 0.5, 0.9, 1.1]]] 


#3차원 “배열”로 바꿔주기
train_X = np.array(train_X, dtype=np.float32)

#올바르게 생성되었는지 확인해보기
print(np.shape(train_X))
print(train_X)

(1, 4, 5)
[[[0.1 4.2 1.5 1.1 2.8]
  [1.  3.1 2.5 0.7 1.1]
  [0.3 2.1 1.5 2.1 0.1]
  [2.2 1.4 0.5 0.9 1.1]]]


In [12]:
rnn = SimpleRNN(3)

In [14]:
hidden_state=rnn(train_X)

In [16]:
print("은닉층: {}, shape: {}".format(hidden_state, hidden_state.shape))

은닉층: [[-0.99983406  0.7856068   0.22183956]], shape: (1, 3)


In [17]:
rnn = SimpleRNN(3, return_sequences=True)

In [19]:
hidden_state=rnn(train_X)

In [20]:
print("은닉층 : {}, shape: {}".format(hidden_state, hidden_state.shape))

은닉층 : [[[ 0.98273146  0.9670011   0.8644497 ]
  [ 0.98643583 -0.17643024  0.4711671 ]
  [ 0.95484823  0.7653335  -0.8967955 ]
  [ 0.9919549  -0.59916824  0.77188826]]], shape: (1, 4, 3)


In [21]:
import numpy as np 



In [22]:
from tensorflow.keras.preprocessing.text import Tokenizer

In [23]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [24]:
from tensorflow.keras.utils import to_categorical

In [25]:
from tensorflow.keras.models import Sequential

In [26]:
from tensorflow.keras.layers import Embedding, Dense, SimpleRNN

In [27]:
text="""경마장에 있는 말이 뛰고 있다\n
그의 말이 법이다\n
가는 말이 고와야 오는 말이 곱다"""


In [28]:
t = Tokenizer()

In [29]:
t.fit_on_texts([text])

In [30]:
vocab_size=len(t.word_index) + 1

In [31]:
print("단어 개수:", vocab_size)

단어 개수: 12


In [32]:
print(t.word_index)

{'말이': 1, '경마장에': 2, '있는': 3, '뛰고': 4, '있다': 5, '그의': 6, '법이다': 7, '가는': 8, '고와야': 9, '오는': 10, '곱다': 11}


In [33]:
sequences = list()

In [35]:
#빈 리스트 만들기
sequences = list()
for line in text.split('\n'):
  #text_to_sequences( )는 텍스트 안의 단어들을 숫자의 시퀀스 형태로 변환한다.
	encoded = t.texts_to_sequences([line])[0]

	for i in range(1, len(encoded)):
		sequence = encoded[:i+1]
		sequences.append(sequence)

print("학습에 사용할 샘플의 개수: %d" %(len(sequences))) 

print(sequences)

학습에 사용할 샘플의 개수: 11
[[2, 3], [2, 3, 1], [2, 3, 1, 4], [2, 3, 1, 4, 5], [6, 1], [6, 1, 7], [8, 1], [8, 1, 9], [8, 1, 9, 10], [8, 1, 9, 10, 1], [8, 1, 9, 10, 1, 11]]


In [61]:
#전체 샘플의 길이 일치 시켜주기(가장 긴 샘플의 길이를 기준으로)
max_len=max(len(l) for l in sequences)
print('샘플 최대의 길이: %d' %max_len)


#전체 샘플의 길이를 6으로 맞춰준다 = padding
#'pre' 옵션을 주면 길이가 6보다 짧은 샘플의 앞에 0을 채운다
sequences = pad_sequences(sequences, maxlen=max_len, padding='pre')

print(sequences)

샘플 최대의 길이: 6
[[ 0  0  0  0  2  3]
 [ 0  0  0  2  3  1]
 [ 0  0  2  3  1  4]
 [ 0  2  3  1  4  5]
 [ 0  0  0  0  6  1]
 [ 0  0  0  6  1  7]
 [ 0  0  0  0  8  1]
 [ 0  0  0  8  1  9]
 [ 0  0  8  1  9 10]
 [ 0  8  1  9 10  1]
 [ 8  1  9 10  1 11]]


In [71]:
sequences = np.array(sequences)

# X에는 리스트의 마지막 값을 제외한 값을 넣고, Y에는 리스트의 마지막 값만 저장(label)
X = sequences[:, :-1] 
Y = sequences[:, -1]

print(Y)

[ 3  1  4  5  1  7  1  9 10  1 11]


In [72]:
sequences = np.array(sequences)

In [73]:
X=sequences[:, :-1]
Y=sequences[:, -1]

print(Y)

[ 3  1  4  5  1  7  1  9 10  1 11]


In [74]:
#원_핫 인코딩
Y=to_categorical(Y, num_classes=vocab_size)

print(Y)

[[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [75]:
model = Sequential()

In [76]:
model.add(Embedding(vocab_size, 10, input_length=max_len-1))

In [77]:
model.add(SimpleRNN(32))

In [78]:
model.add(Dense(vocab_size, activation='softmax'))

In [79]:
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [80]:
model.fit(X,Y, epochs=200, verbose=1)

Epoch 1/200
1/1 [==============================] - 1s 1s/step - loss: 2.4780 - accuracy: 0.0000e+00
Epoch 2/200
1/1 [==============================] - 0s 11ms/step - loss: 2.4621 - accuracy: 0.0909
Epoch 3/200
1/1 [==============================] - 0s 12ms/step - loss: 2.4461 - accuracy: 0.1818
Epoch 4/200
1/1 [==============================] - 0s 7ms/step - loss: 2.4301 - accuracy: 0.3636
Epoch 5/200
1/1 [==============================] - 0s 6ms/step - loss: 2.4139 - accuracy: 0.2727
Epoch 6/200
1/1 [==============================] - 0s 14ms/step - loss: 2.3973 - accuracy: 0.3636
Epoch 7/200
1/1 [==============================] - 0s 8ms/step - loss: 2.3802 - accuracy: 0.3636
Epoch 8/200
1/1 [==============================] - 0s 10ms/step - loss: 2.3626 - accuracy: 0.3636
Epoch 9/200
1/1 [==============================] - 0s 10ms/step - loss: 2.3444 - accuracy: 0.3636
Epoch 10/200
1/1 [==============================] - 0s 9ms/step - loss: 2.3255 - accuracy: 0.3636
Epoch 11/200
1/1 [===

In [55]:
def sentence_generation(model, tokenizer, current_word, n):
  init_word = current_word
  sentence = ''

  for _ in range(n):
    encoded = t.texts_to_sequences([current_word])[0]
    encoded = pad_sequences([encoded], maxlen=5, padding='pre')

    result = model.predict(encoded)
    result = np.argmax(result, axis=1)
  
    for word, index in t.word_index.items():
      if index == result:
        break

    current_word = current_word + ' ' + word
    sentence = sentence + ' ' + word

  sentence = init_word + sentence

  return sentence

In [81]:
#'경마장에' 단어 뒤에 올 4개의 단어를 예측
print(sentence_generation(model, t, '오는', 4))

오는 말이 고와야 오는 말이
